name: Release

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: pnpm/action-setup@v4
      name: Install pnpm
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Restore npm dependencies
      run: pnpm install
    - name: Restore dependencies
      run: dotnet tool restore
    - name: Restore paket dependencies
      run: dotnet paket restore
    - name: Bump
      run: pnpm run bump
    - run: git status
    - run: git --no-pager log
    - name: Get version
      id: package-version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    - run: git add .
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -m "Release v${{env.VERSION}}"
    - run: git tag -a v${{env.VERSION}} -m "See. [CHANGELOG.md](https://github.com/himanoa/fable-effect/blob/main/CHANGELOG.md)"
    - run: git push --tags
    - run: git push origin main
